import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);const {getPaths}=require('../src/paths');const {ConfigStore}=require('../src/store');const {UsageStore}=require('../src/usage');const {Gateway}=require('../src/gateway');

async function listen(handler){const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}`}}
const close=s=>new Promise(r=>s.close(r));
function collectSse(text){return text.split('\n').filter(x=>x.startsWith('data: ')&&x!=='data: [DONE]').map(x=>JSON.parse(x.slice(6)))}

test('chat bridge handles non-stream, streaming text, tool calls, auth, routing, and usage',async t=>{
  const seen=[];const upstream=await listen(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);seen.push({url:req.url,body});res.setHeader('content-type',body.stream?'text/event-stream':'application/json');if(!body.stream)return res.end(JSON.stringify({id:'chat_1',created:1,choices:[{message:{content:'hello'}}],usage:{prompt_tokens:4,completion_tokens:2,total_tokens:6}}));res.write(`data: ${JSON.stringify({choices:[{delta:{content:'hel'}}]})}\n\n`);res.write(`data: ${JSON.stringify({choices:[{delta:{content:'lo'}}]})}\n\n`);res.write(`data: ${JSON.stringify({choices:[{delta:{tool_calls:[{index:0,id:'call_keep',function:{name:'read_file',arguments:'{"pa'}}]}}]})}\n\n`);res.write(`data: ${JSON.stringify({choices:[{delta:{tool_calls:[{index:0,function:{name:'read_file',arguments:'th":"a"}'}}]} }],usage:{prompt_tokens:7,completion_tokens:3,total_tokens:10}})}\n\n`);res.end('data: [DONE]\n\n')});
  t.after(()=>close(upstream.server));const root=fs.mkdtempSync(path.join(os.tmpdir(),'codex-launcher-e2e-'));const paths=getPaths(root);const config=new ConfigStore(paths);config.write({providers:{openrouter:{baseUrl:upstream.url,protocol:'chat'}},selectedModels:[],modelCache:{}});const secrets={get:id=>id==='openrouter'?'secret':null};const usage=new UsageStore(paths);const gateway=new Gateway({configStore:config,secretStore:secrets,usageStore:usage,token:'gateway-secret'});await gateway.start();t.after(()=>gateway.close());
  const unauthorized=await fetch(`${gateway.url}/responses`,{method:'POST',body:'{}'});assert.equal(unauthorized.status,401);
  const headers={'content-type':'application/json',authorization:'Bearer gateway-secret'};
  const non=await fetch(`${gateway.url}/responses`,{method:'POST',headers,body:JSON.stringify({model:'openrouter/vendor/model',input:'hi',reasoning:{effort:'medium'}})});assert.equal(non.status,200);const nonBody=await non.json();assert.equal(nonBody.output[0].content[0].text,'hello');assert.equal(seen[0].body.model,'vendor/model');assert.equal(seen[0].body.reasoning.effort,'medium');
  const stream=await fetch(`${gateway.url}/responses`,{method:'POST',headers,body:JSON.stringify({model:'openrouter/vendor/model',input:'go',stream:true,tools:[{type:'function',name:'read_file',parameters:{type:'object'}}]})});const events=collectSse(await stream.text());assert.equal(events.find(e=>e.type==='response.output_text.done').text,'hello');const done=events.find(e=>e.type==='response.function_call_arguments.done');assert.equal(done.arguments,'{"path":"a"}');const completed=events.find(e=>e.type==='response.completed');const completedCall=completed.response.output.find(x=>x.type==='function_call');assert.equal(completedCall.call_id,'call_keep');assert.equal(completedCall.name,'read_file');assert.equal(usage.query(1).total.total,16);
});

test('native Responses forwarding rewrites model, maps reasoning effort, and tracks non-stream usage',async t=>{
  let seen;const upstream=await listen(async(req,res)=>{let raw='';for await(const c of req)raw+=c;seen=JSON.parse(raw);if(seen.stream){res.writeHead(200,{'content-type':'text/event-stream'});res.end('event: response.completed\ndata: {"type":"response.completed","response":{"usage":{"input_tokens":5,"output_tokens":5,"total_tokens":10}}}\n\ndata: [DONE]\n\n');return}res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'r1',status:'completed',output:[],usage:{input_tokens:8,output_tokens:2,total_tokens:10}}))});t.after(()=>close(upstream.server));const root=fs.mkdtempSync(path.join(os.tmpdir(),'codex-launcher-native-'));const paths=getPaths(root);const config=new ConfigStore(paths);config.write({providers:{deepseek:{baseUrl:upstream.url,protocol:'responses'}},selectedModels:[],modelCache:{}});const usage=new UsageStore(paths);const gateway=new Gateway({configStore:config,secretStore:{get:()=> 'k'},usageStore:usage,token:'t'});await gateway.start();t.after(()=>gateway.close());const headers={'content-type':'application/json',authorization:'Bearer t'};const response=await fetch(`${gateway.url}/responses`,{method:'POST',headers,body:JSON.stringify({model:'deepseek/real-model',input:'x',reasoning:{effort:'medium'}})});assert.equal(response.status,200);assert.equal(seen.model,'real-model');assert.equal(seen.reasoning.effort,'high');assert.equal((await response.json()).model,'deepseek/real-model');const stream=await fetch(`${gateway.url}/responses`,{method:'POST',headers,body:JSON.stringify({model:'deepseek/real-model',input:'x',stream:true,reasoning:{effort:'max'}})});assert.match(await stream.text(),/response.completed/);assert.equal(seen.reasoning.effort,'max');assert.equal(usage.query(1).total.total,20);
});

test('image requests use the configured vision fallback before the selected text model',async t=>{
  const seen=[];const upstream=await listen(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);seen.push(body);res.setHeader('content-type','application/json');if(body.model==='vision-model')return res.end(JSON.stringify({id:'vision',choices:[{message:{content:'A small black square.'}}],usage:{prompt_tokens:20,completion_tokens:5,total_tokens:25}}));res.end(JSON.stringify({id:'text',choices:[{message:{content:'The image is a black square.'}}],usage:{prompt_tokens:12,completion_tokens:6,total_tokens:18}}))});
  t.after(()=>close(upstream.server));const root=fs.mkdtempSync(path.join(os.tmpdir(),'codex-launcher-fallback-'));const paths=getPaths(root);const config=new ConfigStore(paths);config.write({providers:{deepseek:{baseUrl:upstream.url,protocol:'chat'},openrouter:{baseUrl:upstream.url,protocol:'chat'}},selectedModels:[{providerId:'deepseek',id:'text-model',inputModalities:['text']},{providerId:'openrouter',id:'vision-model',inputModalities:['text','image']}],visionFallbackModel:'openrouter/vision-model',modelCache:{}});const usage=new UsageStore(paths);const gateway=new Gateway({configStore:config,secretStore:{get:()=> 'k'},usageStore:usage,token:'t'});await gateway.start();t.after(()=>gateway.close());const response=await fetch(`${gateway.url}/responses`,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer t'},body:JSON.stringify({model:'deepseek/text-model',input:[{role:'user',content:[{type:'input_text',text:'What is shown?'},{type:'input_image',image_url:'data:image/png;base64,abc'}]}],stream:false})});assert.equal(response.status,200);const result=await response.json();assert.equal(result.output[0].content[0].text,'The image is a black square.');assert.equal(seen.length,2);assert.equal(seen[0].model,'vision-model');assert.equal(seen[0].messages.some(message=>Array.isArray(message.content)&&message.content.some(part=>part.type==='image_url')),true);assert.equal(seen[1].model,'text-model');assert.equal(seen[1].messages.some(message=>JSON.stringify(message.content).includes('A small black square.')),true);assert.equal(seen[1].messages.some(message=>JSON.stringify(message.content).includes('image_url')),false);assert.deepEqual(usage.query(1).models.map(item=>item.model),['openrouter/vision-model','deepseek/text-model']);
});

test('native Responses capability errors fall back to Chat and OTLP JSON is ingested securely',async t=>{
  const seen=[];const upstream=await listen(async(req,res)=>{seen.push(req.url);let raw='';for await(const c of req)raw+=c;if(req.url==='/responses'){res.writeHead(404,{'content-type':'application/json'});return res.end(JSON.stringify({error:{message:'Responses API is not supported by this endpoint'}}))}res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'chat-fallback',choices:[{message:{content:'fallback ok'}}],usage:{prompt_tokens:2,completion_tokens:2,total_tokens:4}}))});
  t.after(()=>close(upstream.server));const root=fs.mkdtempSync(path.join(os.tmpdir(),'codex-launcher-protocol-fallback-'));const paths=getPaths(root);const config=new ConfigStore(paths);config.write({providers:{openrouter:{baseUrl:upstream.url,protocol:'responses'}},selectedModels:[],modelCache:{}});const usage=new UsageStore(paths);const gateway=new Gateway({configStore:config,secretStore:{get:()=> 'k'},usageStore:usage,token:'t'});await gateway.start();t.after(()=>gateway.close());
  const headers={'content-type':'application/json',authorization:'Bearer t'};const response=await fetch(`${gateway.url}/responses`,{method:'POST',headers,body:JSON.stringify({model:'openrouter/vendor/model',input:'x'})});assert.equal(response.status,200);assert.equal((await response.json()).output[0].content[0].text,'fallback ok');assert.deepEqual(seen,['/responses','/chat/completions']);assert.equal(gateway.traceStore.query()[0].events.some(event=>event.kind==='protocol.fallback'),true);
  const denied=await fetch(`http://127.0.0.1:${gateway.port}/otel/v1/logs`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(denied.status,401);
  const accepted=await fetch(`http://127.0.0.1:${gateway.port}/otel/v1/logs`,{method:'POST',headers:{'content-type':'application/json','x-codex-launcher-token':'t'},body:JSON.stringify({resourceLogs:[{scopeLogs:[{logRecords:[{traceId:'0123456789abcdef0123456789abcdef',body:{stringValue:'codex.tool_result'}}]}]}]})});assert.equal(accepted.status,200);assert.equal(gateway.traceStore.query().some(group=>group.events.some(event=>event.kind==='codex.tool_result')),true);
});

test('traces expose visible reasoning and tool call inputs and outputs',async t=>{
  const upstream=await listen(async(req,res)=>{for await(const chunk of req)void chunk;res.setHeader('content-type','application/json');res.end(JSON.stringify({id:'trace',choices:[{message:{reasoning_content:'Visible provider summary',content:'done'}}],usage:{prompt_tokens:2,completion_tokens:1,total_tokens:3}}))});
  t.after(()=>close(upstream.server));const root=fs.mkdtempSync(path.join(os.tmpdir(),'codex-launcher-trace-'));const paths=getPaths(root);const config=new ConfigStore(paths);config.write({providers:{openrouter:{baseUrl:upstream.url,protocol:'chat'}},selectedModels:[],modelCache:{}});const gateway=new Gateway({configStore:config,secretStore:{get:()=> 'k'},usageStore:new UsageStore(paths),token:'t'});await gateway.start();t.after(()=>gateway.close());
  const input=[{type:'reasoning',content:[{type:'reasoning_text',text:'prior visible reasoning'}]},{type:'function_call',call_id:'call_1',name:'read_file',arguments:'{"path":"a.txt"}'},{type:'function_call_output',call_id:'call_1',output:'file contents'}];
  const response=await fetch(`${gateway.url}/responses`,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer t'},body:JSON.stringify({model:'openrouter/vendor/model',input})});assert.equal(response.status,200);await response.json();
  const events=gateway.traceStore.query()[0].events;assert.equal(events.some(event=>event.kind==='reasoning.input'&&event.payload.content[0].text==='prior visible reasoning'),true);assert.equal(events.some(event=>event.kind==='tool.call.input'&&event.arguments.includes('a.txt')),true);assert.equal(events.some(event=>event.kind==='tool.call.output'&&event.output==='file contents'),true);assert.equal(events.some(event=>event.kind==='reasoning.output'&&event.payload.content[0].text==='Visible provider summary'),true);
});
